version: "3.8"
services:

  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler

  reporting:
    image: registry.heroku.com/wo-ist-billy/web
    build:
      context: .
      dockerfile: Dockerfile.reporting
