FROM python:3.7.9-buster

ENV ROOT /data/

RUN pip install streamlit

WORKDIR /app
RUN mkdir -p /data/tmp

COPY tmp/latest*.gz /data/tmp/
COPY tmp/products.jsonl /data/tmp/
COPY stores.json /data/
COPY reporting.py ./

CMD ["sh", "-c", "streamlit run --server.port $PORT reporting.py"]
