on:
 workflow_dispatch:
 schedule:
  - cron: "0 */6 * * *"
jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker-compose -f docker-compose.yml build crawler
    - name: crawl
      run: |
        mkdir -p data/iows
        touch data/iows/$(date -u +"%Y-%m-%d").jsonlines.gz;
        tmp_file=$(mktemp)
        docker-compose -f docker-compose.yml run --user "$(id -u):$(id -g)" --volume $tmp_file:/tmp/result.jsonlines --entrypoint=/bin/ash crawler -c "scrapy crawl --loglevel=INFO iows -o /tmp/result.jsonlines"
        gzip --stdout $tmp_file >> data/iows/$(date -u +"%Y-%m-%d").jsonlines.gz
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update iows
