on:
 workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Heroku Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_USR }}
          password: ${{ secrets.HEROKU_PWD }}
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile.reporting
          tags: registry.heroku.com/wo-ist-billy/web:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_PWD }}
        run: |
          heroku container:login
          heroku container:release -a wo-ist-billy web
