on:
 workflow_dispatch:
# schedule:
#  - cron: "0 7 * * *"
jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9.16"
    - name: compute game data
      run: python game-data.py $(date +"%Y-%m-%d")
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update game data 
    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: deploy-pages
